service: ${self:custom.serviceName}-api

provider:
  name: aws
  runtime: nodejs18.x
  region: ${opt:region, 'us-east-1'}
  stage: ${opt:stage, 'dev'}
  timeout: 30
  apiGateway:
    binaryMediaTypes:
      - multipart/form-data
    description: An API to upload images to S3 Bucket and extract information
    request:
      schemas:
        request-model:
          name: RequestModel
          schema: ${file(./src/validator/request.json)}
          description: "A model validation for status request"
        submit-file-model:
          name: SubmitFileModel
          schema:
            type: object
            properties:
              file:
                type: string
                format: binary
          description: "A model validation for file submission"
  deploymentBucket:
    name: ${self:provider.environment.DEPLOY}
  environment:
    LIMIT: 50000000
    SERVICE: submission-portal
    SSM: /${self:service}/${opt:stage, self:provider.stage}
    DEPLOY: mdrijwan-${self:custom.serviceName}-api-${opt:stage, self:provider.stage}
    UPLOAD: mdrijwan-${self:custom.serviceName}-upload-${opt:stage, self:provider.stage}
    TABLE: mdrijwan-${self:provider.environment.SERVICE}-table-${opt:stage, self:provider.stage}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:*
          Resource: arn:aws:s3:::${self:provider.environment.UPLOAD}/*
        - Effect: Allow
          Action:
            - ssm:GetParameter
          Resource: arn:aws:ssm:${self:provider.region}:${self:custom.account}:parameter${self:custom.ssm}
        - Effect: Allow
          Action:
            - dynamodb:*
          Resource: 'arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.TABLE}*'

custom:
  account: ${aws:accountId}
  serviceName: submission-portal
  cognito: ${self:custom.ssm}/cognito
  ssm: ${self:provider.environment.SSM}

configValidationMode: warn

plugins:
  - serverless-plugin-typescript
  - serverless-offline

functions:
  submitFile:
    handler: src/api/submit.handler
    name: submit-file
    description: A lambda handler that uploads file to an S3 bucket and extract data.
    memorySize: 1024
    events:
      - http:
          path: submit
          method: POST
          cors: true
          authorizer:
            arn: arn:aws:cognito-idp:${self:provider.region}:${self:custom.account}:userpool/${ssm:${self:custom.cognito}}


