service: ${self:provider.environment.SERVICE}-data

provider:
  name: aws
  runtime: nodejs18.x
  region: ${opt:region, 'us-east-1'}
  stage: ${opt:stage, 'dev'}
  deploymentBucket:
    name: mdrijwan-${self:provider.stage}-bucket
  environment:
    SERVICE: submission-portal
    DEPLOY: mdrijwan-${self:provider.environment.SERVICE}-api-${opt:stage, self:provider.stage}
    UPLOAD: mdrijwan-${self:provider.environment.SERVICE}-upload-${opt:stage, self:provider.stage}
    TABLE: mdrijwan-${self:provider.environment.SERVICE}-table-${opt:stage, self:provider.stage}

configValidationMode: warn

resources:
  Resources:
    SubmissionUploadBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:provider.environment.UPLOAD}
        PublicAccessBlockConfiguration:
          BlockPublicAcls: false
        OwnershipControls:
          Rules:
            - ObjectOwnership: ObjectWriter
        CorsConfiguration:
          CorsRules:
            - AllowedHeaders:
                - '*'
              AllowedMethods:
                - GET
                - POST
                - PUT
                - DELETE
                - HEAD
              AllowedOrigins:
                - '*'
    SubmissionApiBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:provider.environment.DEPLOY}
        AccessControl: Private
        PublicAccessBlockConfiguration:
          BlockPublicAcls: true
          BlockPublicPolicy: true
          IgnorePublicAcls: true
          RestrictPublicBuckets: true
    SubmissionDynamoDbTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Delete
      Properties:
        TableName: ${self:provider.environment.TABLE}
        AttributeDefinitions:
          - AttributeName: uploadId
            AttributeType: S
          - AttributeName: userId
            AttributeType: S
          - AttributeName: userEmail
            AttributeType: S
        KeySchema:
          - AttributeName: uploadId
            KeyType: HASH
          - AttributeName: userId
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: Submission-Portal-index
            KeySchema:
              - AttributeName: userEmail
                KeyType: HASH
              - AttributeName: userId
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
        BillingMode: PAY_PER_REQUEST
